# Lab 1: NLPScholar practice
### COSC 426: Fall 2025, Colgate University

Use this notebook to answer the questions in `Lab1.md`. For answers where you are looking at data files generated by the `evaluate` or `analyze` modes (which is almost all of them), you should load the data into the ipynb notebook and proceed from there.

## Part 1: Minimal Pair

Feel free to add as many markdown or code chunks as you need.

In [6]:
import pandas as pd
min_pair_byword = pd.read_csv("results/agreement.tsv", sep="\t")
min_pair_byword.head()

,Unnamed: 0,model,lemma,acc,diff,expected,unexpected,macrodiff
0,0,distilbert-base-uncased,BE,1.00,-4.183528,6.040372,10.223900,-4.183528
1,1,distilbert-base-uncased,LIKE,1.00,-2.278638,6.961845,9.240484,-2.278638
2,2,distilgpt2,BE,1.00,-3.058039,5.303710,8.361749,-3.058039
3,3,distilgpt2,LIKE,0.75,-1.516576,8.794077,10.310652,-1.516576
4,4,gpt2,BE,1.00,-3.240781,5.350453,8.591234,-3.240781

In [7]:
min_pairs_like = min_pair_byword[min_pair_byword["lemma"] == "LIKE"]
min_pairs_like.head()

,Unnamed: 0,model,lemma,acc,diff,expected,unexpected,macrodiff
1,1,distilbert-base-uncased,LIKE,1.00,-2.278638,6.961845,9.240484,-2.278638
3,3,distilgpt2,LIKE,0.75,-1.516576,8.794077,10.310652,-1.516576
5,5,gpt2,LIKE,0.75,-1.550592,8.680153,10.230745,-1.550592

## Part 2: Token Classification

Feel free to add as many markdown or code chunks as you need.

In [52]:
ner_file = pd.read_csv("results/ner_bycond.tsv", sep="\t")
ner_file.head()

,Unnamed: 0,model,micro-precision,micro-recall,micro-f1,macro-precision,macro-recall,macro-f1,accuracy
0,0,distilbert-base-uncased,0.35,0.304348,0.325581,0.177083,0.093056,0.121981,0.304348

In [53]:
#TOTAL ACCURACY OF THE MODEL
total_accuracy = ner_file["accuracy"]
print(total_accuracy) # correct answer

0.2545454545454545
55
0    0.304348
Name: accuracy, dtype: float64

In [61]:
#Question... 2
#ACCURACY OF THE MODEL IGNORING "O"
onlyO_results = pd.read_csv("results/ner_onlyO_bycond.tsv", sep="\t")
onlyO_results.head()

accuracy_onlyO = onlyO_results["accuracy"]
print(accuracy_onlyO)

0    0.08
Name: accuracy, dtype: float64

In [58]:
#Question... 3
#ACCURACY OF THE MODEL IGNORING "0" AND PUNCTUATION
noOP_results = pd.read_csv("results/ner_noO_bycond.tsv", sep="\t")
noOP_results.head()

accuracy_noOP = noOP_results["accuracy"]
print(accuracy_noOP)

0    0.125
Name: accuracy, dtype: float64

## Part 3: Text Classification

Feel free to add as many markdown or code chunks as you need.